version: '3.6'
services:
  app:
    build:
      context: '.'
    environment:
      REDIS_URL: 'redis://redis:6379/1'
      SLACK_SECRET_TOKEN:
    networks:
      kuniklo_network:
        ipv4_address: '192.168.144.3'
    extra_hosts:
      - 'redis:192.168.144.2'
    depends_on:
      - 'redis'
    command: ['bundle', 'exec', 'lita']
  redis:
    image: 'redis:3.2'
    container_name: 'kuniklo-bot-redis'
    ports:
      - '16379:6379'
    volumes:
      - 'kuniklo-bot-redis-vol:/data'
    networks:
      kuniklo_network:
        ipv4_address: '192.168.144.2'

volumes:
  kuniklo-bot-redis-vol: {}

networks:
  kuniklo_network:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '192.168.144.0/24'
